config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|uk/ do
    root to: "departments#index"
    # get '/:locale' => 'departments#index'

    resources :positions
    resources :employees
    resources :departments

    get "departments/:id/employees", to: "departments#employees"

    resources :employees do
      resources :position_histories, only: [:new, :create, :edit, :update]
      resources :vacations, only: [:new, :create]
    end
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :department

  has_many :vacations
  has_many :position_histories
  has_many :positions, through: :position_histories

  validates :last_name, presence: true, length: { minimum: 2, maximum: 30 }
  validates :first_name, presence: true, length: { minimum: 2, maximum: 30 }
  validates :middle_name, presence: true, length: { minimum: 2, maximum: 30 }
  validates :passport_data, presence: true, length: { is: 9 }
  validates :date_of_birth, presence: true, timeliness: { before: 18.years.ago }
  validates :place_of_birth, presence: true, format: { with: /\A[a-zA-Z\s]+\z/ }
  validates :home_address, presence: true, format: { with: /\A\d+\s[A-z0-9]+\s[A-z]+\z/ }
  validate :department_is_open, on: :create

  EMPLOYEE_LIMIT = 20

  def vacation_days
    positions&.last&.vacation_days || 0
  end

  def remaining_vacation_days
    vacation_days - used_vacation_days
  end

  def years_of_employment
    return 0 unless started_last_position
    DateTime.now.year - started_last_position.year
  end

  def started_last_position
    position_histories.last&.started_on
  end

  def used_vacation_days
    return 0 unless started_last_position
    count = 0
    start = started_last_position + years_of_employment.years
    end_on = start + 1.year
    vacations.where(started_on: start..end_on).each do |vacation|
      count += (vacation.finished_on - vacation.started_on).to_i
    end
    count
  end

  def department_is_open
    if department.employees.count >= EMPLOYEE_LIMIT
      errors.add(:base, :employee_limit, count: EMPLOYEE_LIMIT)
    end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :find_employee, only: [:edit, :update, :destroy]

  def index
    @employees = Employee.all
  end

  def show
    @employee = Employee.find(params[:id]).decorate

    @vacation = Vacation.new
    @vacations = @employee.vacations
    @total_vacation_days = @employee.total_vacation_days
    @salary = @employee.calculate_salary

    @position_history = PositionHistory.new
    @position = @employee.position_histories.last
    @position_histories = @employee.position_histories
    @last_position = @employee.last_position
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to @employee
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @employee.update(employee_params)
      redirect_to @employee
    else
      render :edit
    end
  end

  def destroy
    @employee.destroy
  end

  private

  def find_employee
    @employee = Employee.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(:first_name, :middle_name, :last_name, :passport_data, :date_of_birth, :place_of_birth, :home_address, :department_id)
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, url: employee.persisted? ? employee_path(employee) : employees_path, data: { turbo: false }) do |f| %>

    <p><%= t('views.employees.form.first_name') %></p>
    <%= f.text_field :first_name %>

    <p><%= t('views.employees.form.last_name') %></p>
    <%= f.text_field :last_name %>

    <p><%= t('views.employees.form.middle_name') %></p>
    <%= f.text_field :middle_name %>

    <p><%= t('views.employees.form.passport_data') %></p>
    <%= f.text_field :passport_data %>

    <p><%= t('views.employees.form.date_of_birth') %></p>
    <%= f.date_field :date_of_birth %>

    <p><%= t('views.employees.form.place_of_birth') %></p>
    <%= f.text_field :place_of_birth %>

    <p><%= t('views.employees.form.home_address') %></p>
    <%= f.text_field :home_address %>

    <% if employee.new_record? %>
        <p><%= t('views.employees.form.department_id') %></p>
        <%= f.collection_select :department_id, Department.all, :id, :name, prompt: t('views.employees.form.select_department') %>
    <% end %>

    <%= f.submit employee.persisted? ? t('views.employees.form.update_employee') : t('views.employees.form.create_employee') %>
<% end %>

app/views/employees/edit.html.erb
<h1><%= t('views.employees.edit.title') %></h1>

<%= render 'form', employee: @employee %>

<%= render 'shared/errors_messages', object: @employee %>

app/views/employees/index.html.erb
<h1><%= t('views.employees.index.title') %></h1>
<h2><%= t('views.employees.index.description') %></h2>

<%= link_to t('views.employees.index.add_employee'), new_employee_path %>

<h3>Numebr on Employees: <%= @employees.count %></h3>

<% @employees.each do |employee| %>
    <%= link_to employee.first_name, employee %>
    <%= link_to t('views.employees.index.edit'), edit_employee_path(employee) %>
    <%= button_to t('views.employees.index.delete'), employee_path(employee), method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
<% end %>

app/views/employees/new.html.erb
<h1><%= t('views.employees.new.title') %></h1>

<%= render 'form', employee: @employee %>

<%= render 'shared/errors_messages', object: @employee %>

app/views/employees/show.html.erb
<div class="user_info">
    <h1><%= @employee.last_name %></h1>
    <h1><%= @employee.first_name %></h1>
    <h1><%= @employee.middle_name %></h1>
</div>
<div class="user_info">
    <h3><%= t('views.employees.show.position') %>: <%= @last_position %></h3>
    <h3><%= t('views.employees.show.salary') %>: <%= @salary %></h3>
    <p><%= t('views.employees.show.department_id') %>: <%= @employee.department_id %></p>
</div>
<hr/>
<p><%= t('views.employees.show.employee_id') %>: <%= @employee.id %></p>
<p><%= t('views.employees.show.passport_data') %>: <%= @employee.passport_data %></p>
<hr/>
<div class="user_info">
    <p><%= t('views.employees.show.date_of_birth') %>: <%= @employee.date_of_birth %></p>
    <p><%= t('views.employees.show.place_of_birth') %>: <%= @employee.place_of_birth %></p>
</div>
<hr/>
<p><%= t('views.employees.show.home_address') %>: <%= @employee.home_address %></p>
<h1>----- <%= t('views.employees.show.position_history') %></h1>

<h4><%= t('views.employees.show.add_position') %></h4>
<%= form_with(model: @position_history, data: { turbo: false }, url: employee_position_histories_path(@employee)) do |f| %>
    <%= f.collection_select :position_id, Position.all, :id, :name, prompt: t('views.employees.show.select_position') %>
    <%= f.label t('views.employees.show.started_on') %>
    <%= f.date_field :started_on %>
    <%= f.label t('views.employees.show.finished_on') %>
    <%= f.date_field :finished_on %>
    <%= f.hidden_field :employee_id, value: @employee.id %>
    <%= f.submit t('views.employees.show.submit') %>
<% end %>

<% if flash[:position_errors] %>
 <p><%= flash[:position_errors].join(', ') %></p>
<% end %>
<br>

<% if @position %>
    <%= link_to t('views.employees.show.edit'), edit_employee_position_history_path(@employee, @position) %>
<% end %>
<br>
<% @position_histories.reverse.each do |position_history| %>
    <tr>
        <td><%= t('views.employees.show.position') %>: <%= position_history.position.name %></td>
        <br>
        <td><%= t('views.employees.show.started_on') %>: <%= position_history.started_on %></td>
        <br>
        <td><%= t('views.employees.show.finished_on') %>: <%= position_history.finished_on %></td>
    </tr>
    <hr>
    <br>
<% end %>

<br>
<br>

<h2><%= t('views.employees.show.vacations_list') %></h2>
<br>
<h4><%= t('views.employees.show.add_vacation') %></h4>
<%= form_with(model: @vacation, data: { turbo: false }, url: employee_vacations_path(@employee)) do |f| %>
    <%= f.label t('views.employees.show.started_on') %>
    <%= f.date_field :started_on %>
    <%= f.label t('views.employees.show.finished_on') %>
    <%= f.date_field :finished_on %>
    <%= f.hidden_field :employee_id, value: @employee.id %>
    <%= f.submit t('views.employees.show.add_vacation') %>
<% end %>

<% if flash[:error] %>
    <p><%= flash[:error].join(', ') %></p>
<% end %>

<br>

<h3><%= t('views.employees.show.total_vacation_days') %>: <%= @total_vacation_days %></h3>
<br>
<% @vacations.reverse.each do |vacation| %>
    <p><%= vacation.started_on %> - <%= vacation.finished_on %></p>
<% end %>