config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|uk/ do
    root to: "departments#index"
    # get '/:locale' => 'departments#index'

    resources :positions
    resources :employees
    resources :departments

    get "departments/:id/employees", to: "departments#employees"

    resources :employees do
      resources :position_histories, only: [:new, :create, :edit, :update]
      resources :vacations, only: [:new, :create]
    end
  end
end

app/models/position.rb
class Position < ApplicationRecord
  has_many :position_histories, dependent: :destroy
  has_many :employees, through: :position_histories

  MANAGER = "manager"

  validates :name, presence: true, length: { minimum: 4, maximum: 120 }
  validates :salary, presence: true, numericality: { greater_than: 0 }
  validates :vacation_days, presence: true, numericality: { only_integer: true }
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :find_position, only: [:show, :edit, :update, :destory]

  def index
    @positions = Position.all
  end

  def show
  end

  def new
    @position = Position.new
  end

  def create
    @position = Position.new(position_params)
    if @position.save
      redirect_to @position
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @position.update(position_params)
      redirect_to @position
    else
      render :edit
    end
  end

  def destroy
    @position.destroy
  end

  private

  def find_position
    @position = Position.find(params[:id])
  end

  def position_params
    params.require(:position).permit(:name, :salary, :vacation_days)
  end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_form.html.erb
<%= form_with(model: @position, data: { turbo: false }, url: @position.persisted? ? position_path(@position) : positions_path) do |f| %>
    <p><%= t('views.position.form.name') %></p>
    <%= f.text_field :name %>

    <p><%= t('views.position.form.salary') %></p>
    <%= f.text_field :salary %>

    <p><%= t('views.position.form.vacation_days') %></p>
    <%= f.text_field :vacation_days %>

    <%= f.submit @position.persisted? ? t('views.position.form.update') : t('views.position.form.create') %>
<% end %>

app/views/positions/edit.html.erb
<h1><%= t('views.position.edit.title') %></h1>

<%= render 'form', object: @position %>

<%= render 'shared/errors_messages', object: @position %>

app/views/positions/index.html.erb
<h1><%= t('views.position.index.title') %></h1>
<h2><%= t('views.position.index.description') %></h2>

<%= link_to "New Position", new_position_path %>

<h3><%= t('views.position.index.positions_number') %>:  <%= @positions.count %></h3>

<% @positions.each do |position| %>
    <%= link_to position.name, position %>
    <%= link_to t('views.position.index.edit'), edit_position_path(position) %>
    <%= button_to t('views.position.index.delete'), position_path(position), method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
<% end %>

app/views/positions/new.html.erb
<h1><%= t('views.position.new.title') %></h1>

<%= render 'form', position: @position %>

<%= render 'shared/errors_messages', object: @position %>

app/views/positions/show.html.erb
<h1><%= t('views.position.show.title') %></h1>

<p><%= t('views.position.show.id') %>: <%= @position.id %></p>/
<p><%= t('views.position.show.name') %>: <%= @position.name %></p>/
<p><%= t('views.position.show.salary') %>: <%= @position.salary %></p>
<p><%= t('views.position.show.vacation_days') %>: <%= @position.vacation_days %></p>

<%= link_to t('views.position.show.edit'), edit_position_path %>