config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|uk/ do
    root to: "departments#index"
    # get '/:locale' => 'departments#index'

    resources :positions
    resources :employees
    resources :departments

    get "departments/:id/employees", to: "departments#employees"

    resources :employees do
      resources :position_histories, only: [:new, :create, :edit, :update]
      resources :vacations, only: [:new, :create]
    end
  end
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :employees, dependent: :destroy

  validates :name, presence: true, uniqueness: true, length: { minimum: 6, maximum: 120 }
  validates :abbreviation, presence: true, length: { minimum: 40, maximum: 400 }
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :find_department, only: [:show, :edit, :update, :destroy, :employees]

  def index
    @departments = Department.all
  end

  def show
    @employees = @department.employees
  end

  def new
    @department = Department.new
  end

  def create
    @department = Department.new(department_params)
    if @department.save
      redirect_to @department
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @department.update(department_params)
      redirect_to @department
    else
      render :edit
    end
  end

  def destroy
    @department.destroy
  end

  def employees
  end

  private

  def find_department
    @department = Department.find(params[:id])
  end

  def department_params
    params.require(:department).permit(:name, :abbreviation)
  end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_form.html.erb
<%= form_with(model: @department, data: { turbo: false }, url: @department.persisted? ? department_path(@department) : departments_path) do |f| %>
    <p><%= t('views.department.form.name') %></p>
    <%= f.text_field :name %>

    <p><%= t('views.department.form.abbreviation') %></p>
    <%= f.text_field :abbreviation %>

    <%= f.submit department.persisted? ? t('views.department.form.update') : t('views.department.form.create') %>
<% end %>

app/views/departments/edit.html.erb
<h1><%= t('views.department.edit.title') %></h1>

<%= render 'form', department: @department %>

<%= render 'shared/errors_messages', object: @department %>

app/views/departments/employees.html.erb
<h1><%= link_to "#{@department.name}", @department %> <%= t('views.department.employees.title') %></h1>

<% @department.employees.each do |employee| %>

    <% employee_decorated = employee.decorate %>

    <h3><%= link_to "#{employee.first_name} #{employee.last_name}", employee %>:</h3>
    <ul>
        <% employee.vacations.each do |vacation| %>
            <li><%= vacation.started_on %> - <%= vacation.finished_on %></li>
        <% end %>
        <h4><%= t('views.department.employees.total_vacations') %>: <%= employee_decorated.total_vacation_days %></h4>
    </ul>
<% end %>

app/views/departments/employees_list.html.erb
<h1><%= link_to "#{@department.name}", @department %> department employees vacations list</h1>

<% @department.employees.each do |employee| %>

    <% employee_decorated = employee.decorate %>

    <h3><%= link_to "#{employee.first_name} #{employee.last_name}", employee %>:</h3>
    <ul>
        <% employee.vacations.each do |vacation| %>
            <li><%= vacation.started_on %> - <%= vacation.finished_on %></li>
        <% end %>
        <h4>Total vacation days: <%= employee_decorated.total_vacation_days %></h4>
    </ul>
<% end %>

app/views/departments/index.html.erb
<h1><%= t('views.department.index.title') %></h1>
<h2><%= t('views.department.index.description') %></h2>

<%= link_to t('views.department.index.new_department'), new_department_path %>

<h2><%= t('views.department.index.departments_number') %>: <%= @departments.count %></h2>

<% @departments.each do |department| %>
    <% department_decorator = department.decorate %>
    <% if department_decorator.current_manager %>
        <% manager = department_decorator.current_manager %>
        <p><%= t('views.department.index.department_manager') %>: <%= link_to "#{manager.first_name} #{manager.last_name}", manager %></p>
    <% else %>
        <p><%= t('views.department.index.no_manager') %></p>
    <% end %>

    <%= link_to department.name, department %>
    <p><%= t('views.department.index.department_employees_number') %>: <%= department.employees.count %></p>
    <%= link_to t('views.department.index.edit'), edit_department_path(department) %>
    <%= button_to t('views.department.index.delete'), department_path(department), method: :delete, data: { turbo_method: :delete, turbo_confirm: t('views.department.index.confirmation') } %>
    <hr>
<% end %>

app/views/departments/new.html.erb
<h1><%= t('views.department.new.title') %></h1>

<%= render 'form', department: @department %>

<%= render 'shared/errors_messages', object: @department %>

app/views/departments/show.html.erb
<h1><%= t('views.department.show.title') %></h1>

<p><%= t('views.department.show.department_id') %>: <%= @department.id %></p>
<p><%= t('views.department.show.department_name') %>: <%= @department.name %></p>
<p><%= t('views.department.show.department_abbreviation') %>: <%= @department.abbreviation %></p>

<%= link_to t('views.department.show.edit'), edit_department_path %>
<hr />
<br>
<%= link_to t('views.department.show.add_employees'), new_employee_path %>
<br>
<%= link_to t('views.department.show.employee_vacations'), "/departments/#{@department.id}/employees" %>

<h2><%= t('views.department.show.department_employees') %></h2>
<% @employees.each do |employee| %>
    <div class="user_info">
        <li><%= link_to "#{employee.first_name} #{employee.last_name}", employee_path(employee) %></li>
        <p><%= employee.position_histories.last&.position&.name %></p>
    </div>
<% end %>